---
version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - forbidigo
    - misspell
    - sloglint
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (io.ReadCloser).Close

formatters:
  enable:
    - gofumpt
